server:
  port: 9095
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marszm/microservices-config-store
          search-paths:
            - '*service'
